image:
  - Ubuntu1804

matrix:
  fast_finish: true

build_script:
  - cmake --version
  - mkdir google-benchmark && cd google-benchmark
  - git clone https://github.com/google/benchmark.git
  - git clone https://github.com/google/googletest.git benchmark/googletest
  - cd benchmark
  - mkdir build && cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=RELEASE
  - make
  - sudo make install
  - cd ..
  - cd ..
  - cd ..
  - mkdir build && cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_BENCHMARK=ON
  - make